apiVersion: apps/v1
kind: Deployment # Deployment object
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers: # Containers that will run inside the pod
        - name: postgres
          image: postgres:15 # Docker Image for the PostgreSQL database
          ports:
            - containerPort: 5432
          env:  # Environment variables to securely pass values.
            - name: POSTGRES_DB
              value: "recipe_app_db"
            - name: POSTGRES_USER
              value: "app_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password-secret
                  key: password
          volumeMounts: # To link the container to volumes
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql # To mount the configmap (only init.sql)
              subPath: init.sql
      volumes: # Two storage volumes for the pod
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgres-initdb
          configMap:
            name: postgres-init-configmap # To configure the dB