apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service-deployment
  labels:
    app: recipe-service
spec:
  replicas: 1 # Scaling factor
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
      - name: recipe-service
        image: hemanthanne411/recipe-service:latest
        ports:
        - containerPort: 6002 # allow traffic to this port to be routed to flask app
        env: # Same env values 
        - name: POSTGRES_DB
          value: "recipe_app_db"
        - name: POSTGRES_USER
          value: "app_user"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: # Getting password (env value) from secret object
              name: postgres-password-secret
              key: password
