apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service # To route the network traffic to this user-service
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
      nodePort: 30001
  type: NodePort